server:
    port: 8001
spring:
    application:
        name: IntraEdge
info:
    project:
        version: 0.1
logging:
  level:
      org.springframework: INFO
      org.hibernate: INFO
      com.sms: INFO